//==================================================================================
//==================================================================================
// File: HardwareAndCo.cpp
// Description: Centralized initialization and management of PENDA
//              hardware resources and software components (TFT display, GUI,
//              DSP modules, etc.)
//
// Copyright (c) 2025-2026 DadDesign-Project.
//==================================================================================
//==================================================================================
#include "PersistentDefine.h"
#include "HardwareAndCoDefines.h"
#include "@options.h"
#include "@EffectsConfig.h"

//**********************************************************************************
// External handles (generated by CubeMX)
//**********************************************************************************
extern QSPI_HandleTypeDef hqspi;               // QSPI flash interface handle
extern SAI_HandleTypeDef  hsai_BlockA1;        // SAI block A1 for audio
extern SAI_HandleTypeDef  hsai_BlockB1;        // SAI block B1 for audio
extern DMA_HandleTypeDef  hdma_sai1_a;         // DMA for SAI A
extern DMA_HandleTypeDef  hdma_sai1_b;         // DMA for SAI B
extern SPI_HandleTypeDef  hspi1;               // SPI for display
extern DMA_HandleTypeDef  hdma_spi1_tx;        // DMA for SPI transmit
extern UART_HandleTypeDef huart1;              // UART for MIDI
extern DMA_HandleTypeDef  hdma_usart1_rx;      // DMA for UART receive
extern TIM_HandleTypeDef  htim6;			   // Timer for softSPI


//**********************************************************************************
// Global instances
//**********************************************************************************

// SDRAM
#include "IS42S16320.h"

// Flash memory instance
#include "W25Q128.h"
DadDrivers::cW25Q128 __Flash;

// Persistent storage instances
#include "cFlasherStorage.h"
QFLASH_FLASHER  DadPersistentStorage::cFlasherStorage __FlasherStorage;
#include "cBlockStorageManager.h"
QFLASH_TABSAVE  uint8_t      						  __TabSaveBlock[BLOCK_STORAGE_MEM_SIZE];
DadPersistentStorage::cBlockStorageManager            __BlockStorageManager(__TabSaveBlock);
// -------------------------------------------------------------------
// Persistent Target — reserved in QFLASH_LOADER flash section
QFLASH_LOADER uint8_t __LoaderInfo[QFLAH_SECTOR_SIZE];

// Display instance
#include "cDisplay.h"
DECLARE_DISPLAY(__Display);

// Switch instances
#include "cSwitch.h"
DadDrivers::cSwitch __Switch1;
DadDrivers::cSwitch __Switch2;

// Encoder instances
#include "cEncoder.h"
DadDrivers::cEncoder __Encoder1;
DadDrivers::cEncoder __Encoder2;
DadDrivers::cEncoder __Encoder3;
DadDrivers::cEncoder __Encoder0;

// SoftSPI instance
#include "cSoftSPI.h"
DadDrivers::cSoftSPI __SoftSPI;

// Dry/Wet instance
#include "cDryWet.h"
DadDrivers::cDryWet  __DryWet;

// Bypass on off manager
#include "cBypassOnOffManager.h"
DadGUI:: cBypass_On_Off_Manager __BypassOnOffManagerImpl;
DadGUI::iBypassOnOffManager* __pBypassOnOffManager = &__BypassOnOffManagerImpl;

// MIDI interface instance
#include "cMidi.h"
DadDrivers::cMidi __Midi;

// GUI instance
#include "MainGUI.h"
DadGUI::cMainGUI __GUI;

// MPU Config
extern void MPU_Config(void);

// Background layer declaration for display
DECLARE_LAYER(BackLayer, SCREEN_WIDTH, SCREEN_HEIGHT);

// Effect Instantiation
DECLARE_EFFECT;

//**********************************************************************************
// HAL_TIM_PeriodElapsedCallback
// Timer interrupt callback for SoftSPI updates
//**********************************************************************************
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
    if (htim->Instance == TIM6) {
        __SoftSPI.TimerCallback();  // Update SoftSPI state
    }
}

//**********************************************************************************
// HardwareAndCoInitialize
// Initializes all hardware peripherals in the correct order
//**********************************************************************************
void HardwareAndCoInitialize() {

	// Initialize SDRAM memory
	IS42S16320_Initialize();

    // Initialize QSPI flash memory
    if (HAL_OK != __Flash.Init(&hqspi, DOUBLE_MODE, FLASH_ADDRESS)) {
        Error_Handler();
    }

    // Configure Memory Protection Unit
    MPU_Config();

    // Invalidate CPU caches for memory consistency
    SCB_InvalidateDCache();
    SCB_InvalidateICache();

	// Initialize persistent storage and check if initialization is needed
    bool NeedInitBlockStorage = __BlockStorageManager.Init(EFFECT_BUILD);

    // Initialize display
    INIT_DISPLAY(__Display, &hspi1);
    __Display.setOrientation(Rotation::Degre_90);

    // Initialize GUI system
    __GUI.Initialize();

    // Initialize foot switches with debouncing parameters
    constexpr uint32_t kUpdateTime      = static_cast<uint32_t>(RT_RATE * 0.03f);   // 30ms debounce
    constexpr uint32_t kMinPeriod       = static_cast<uint32_t>(RT_RATE * 0.15f);   // 150ms min valid press
    constexpr uint32_t kMaxPeriod       = static_cast<uint32_t>(RT_RATE * 1.1f);    // 1.1s max hold
    constexpr uint32_t kAbortMaxPeriod  = static_cast<uint32_t>(RT_RATE * 1.5f);    // 1.5s timeout

    __Switch1.Init(FootSwitch1_GPIO_Port, FootSwitch1_Pin,
                   RT_RATE, kUpdateTime, kMinPeriod, kMaxPeriod, kAbortMaxPeriod);

    __Switch2.Init(FootSwitch2_GPIO_Port, FootSwitch2_Pin,
                   RT_RATE, kUpdateTime, kMinPeriod, kMaxPeriod, kAbortMaxPeriod);

    // Initialize rotary encoders
    constexpr uint32_t EncoderUpdatePeriodMs = RT_RATE * 0.001f; // 1ms update
    constexpr uint32_t SwitchUpdatePeriodMs  = RT_RATE * 0.005f; // 5ms switch check

    __Encoder3.Init(Encoder1_A_GPIO_Port, Encoder1_A_Pin,
                    Encoder1_B_GPIO_Port, Encoder1_B_Pin,
                    Encoder1_SW_GPIO_Port, Encoder1_SW_Pin,
                    EncoderUpdatePeriodMs, SwitchUpdatePeriodMs);

    __Encoder2.Init(Encoder2_A_GPIO_Port, Encoder2_A_Pin,
                    Encoder2_B_GPIO_Port, Encoder2_B_Pin,
                    Encoder2_SW_GPIO_Port, Encoder2_SW_Pin,
                    EncoderUpdatePeriodMs, SwitchUpdatePeriodMs);

    __Encoder1.Init(Encoder3_A_GPIO_Port, Encoder3_A_Pin,
                    Encoder3_B_GPIO_Port, Encoder3_B_Pin,
                    Encoder3_SW_GPIO_Port, Encoder3_SW_Pin,
                    EncoderUpdatePeriodMs, SwitchUpdatePeriodMs);

    __Encoder0.Init(Encoder0_A_GPIO_Port, Encoder0_A_Pin,
                    Encoder0_B_GPIO_Port, Encoder0_B_Pin,
                    Encoder0_SW_GPIO_Port, Encoder0_SW_Pin,
                    EncoderUpdatePeriodMs, SwitchUpdatePeriodMs);

    // Initialize software SPI for external peripherals
    __SoftSPI.Initialize(SSPI_DATA_GPIO_Port, SSPI_DATA_Pin,
                         SSPI_CLK_GPIO_Port, SSPI_CLK_Pin,
                         SSPI_CS_GPIO_Port, SSPI_CS_Pin,
                         &htim6);

    HAL_TIM_Base_Start_IT(&htim6); // Enable periodic SoftSPI callback

    // DryWet Manager initialization
    __DryWet.Init(MIN_DRY, MAX_DRY, FAD_TIME);

    // Effect state manager
    __pBypassOnOffManager->Initialize();

    // Initialize MIDI interface
    __Midi.Initialize(&huart1, 0);

    // Load and display splash screen from flash
    uint8_t* ImgPtr;
    uint8_t  NbFrame;
    uint16_t Width;
    uint16_t Height;
    __FlasherStorage.GetImgInformation(EFFECT_SPLATCH_SCREEN, ImgPtr, NbFrame, Width, Height);
    DadGFX::cImageLayer* SplatchLayer = nullptr;

    if(ImgPtr){
        SplatchLayer = __Display.addLayer(ImgPtr, 0, 0, Width, Height, 1, NbFrame);
        SplatchLayer->changeZOrder(2);
    }

    // Create background layer for initialization messages
    DadGFX::cLayer* BackLayer = ADD_LAYER(__Display, BackLayer, 0, 0, 2);
    BackLayer->changeZOrder(3);
    BackLayer->eraseLayer();
    __Display.flush();

    // Display initialization message if storage needs initialization
    if(NeedInitBlockStorage){
        constexpr uint16_t WidthBox = 200;
        constexpr uint16_t HeightBox = 120;
        constexpr uint16_t xBox = (SCREEN_WIDTH - WidthBox ) / 2;
        constexpr uint16_t yBox = (SCREEN_HEIGHT - HeightBox) / 2;
        constexpr uint16_t xHalfBox = SCREEN_WIDTH / 2;
        constexpr uint16_t yHalfBox = SCREEN_HEIGHT / 2;
        constexpr uint16_t yOffset = 50;

        const char* Text1 = "Please wait...";
        const char* Text2 = "Initializing";
        const char* Text3 = "flash memory.";

        // Draw initialization dialog box
        BackLayer->drawFillRect(xBox, yBox, WidthBox, HeightBox, DadGUI::__ThemesManager->SplatchBack);

        // Display initialization text
        BackLayer->setFont(FONTMB);
        uint16_t TextWidth = BackLayer->getTextWidth(Text1);
        BackLayer->setCursor(xHalfBox - TextWidth/2, yHalfBox - yOffset);
        BackLayer->setTextFrontColor(DadGUI::__ThemesManager->SplatchText);
        BackLayer->drawText(Text1);

        BackLayer->setFont(FONTS);
        TextWidth = BackLayer->getTextWidth(Text2);
        BackLayer->setCursor(xHalfBox - TextWidth/2, yHalfBox);
        BackLayer->setTextFrontColor(DadGUI::__ThemesManager->SplatchText);
        BackLayer->drawText(Text2);

        TextWidth = BackLayer->getTextWidth(Text3);
        BackLayer->setCursor(xHalfBox - TextWidth/2, yHalfBox + 20);
        BackLayer->setTextFrontColor(DadGUI::__ThemesManager->SplatchText);
        BackLayer->drawText(Text3);

        __Display.flush();

        // Initialize flash memory storage
        __BlockStorageManager.InitializeMemory(EFFECT_BUILD);
        HAL_Delay(400);
    } else {
        __Display.flush();
        HAL_Delay(1000);
    }

    // Clean up initialization layers
    BackLayer->changeZOrder(0);
    if(SplatchLayer){
        SplatchLayer->changeZOrder(0);
    }


    // Initialize audio effect processing
    __Effect.Initialize();

    // Start GUI system
    __GUI.Start();

	if (HAL_OK != StartAudio(&hsai_BlockA1, &hsai_BlockB1)) {
			Error_Handler();
    }

    // Start GUI system
    __GUI.MainLoop();
}

// =============================================================================
// Real-time Audio Processing
// =============================================================================

//**********************************************************************************
// AudioCallback
// Real-time audio processing function executed by the audio engine
//**********************************************************************************
void AudioCallback(AudioBuffer *pIn, AudioBuffer *pOut) {

#ifdef MONITOR
    __GUI.startRTMonitoring(); // Start performance monitoring
#endif

    // Update activity counter for LED heartbeat
    __GUI.notifyRTActivity();

    // Update all input devices in real-time
    __Switch1.Debounce();
    __Switch2.Debounce();
    __Encoder1.Debounce();
    __Encoder2.Debounce();
    __Encoder3.Debounce();
    __Encoder0.Debounce();

    // Process audio buffer samples
    for (size_t i = 0; i < AUDIO_BUFFER_SIZE; i++) {
    	bool Silence = ((fabs(pIn->Right) + fabs(pIn->Left)) < 0.01f);

        // Process audio through GUI and effect chain
        DadGUI::__GUI_EventManager.sendEventToActive_RT_ProcessIn(pIn);
        __Effect.Process(pIn, pOut, __pBypassOnOffManager->getTargetState(), Silence);
        DadGUI::__GUI_EventManager.sendEventToActive_RT_Process();
        DadGUI::__GUI_EventManager.sendEventToActive_RT_ProcessOut(pOut);

        // Advance buffer pointers
        pOut++;
        pIn++;
    }

#ifdef MONITOR
    __GUI.stopRTMonitoring(); // Stop performance monitoring
#endif
}


//***End of file**************************************************************




